# TODO: add linting bots
name: Chromatic
on: [pull_request]

jobs:
  chromatic:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - run: |
        yarn && yarn build
    - uses: chromaui/action@v1
      with: 
        projectToken: err110fciri
        token: ${{ secrets.GITHUB_TOKEN }}