# TODO: add linting bots
name: Chromatic
on: [pull_request]

jobs:
  chromatic:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - run: |
        yarn && yarn build
    - uses: chromaui/action@v1
      with: 
        projectToken: err110fciri
        token: ${{ secrets.GITHUB_TOKEN }}
    - name: Upload build log
      if: ${{ always() }} # fuck you, why don't you work???
      uses: actions/upload-artifact@v2
      with:
        name: buildlogs
        path: /home/runner/work/transcribely/transcribely/build-storybook.log