name: "Chromatic"
on: push

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - run: |
        npm build
    - uses: chromaui/action@v1
      with: 
        projectToken: err110fciri
        token: ${{ secrets.CHROMATIC }}